### PR TITLE
Update SIS2 to use the new IO interface

### PR DESCRIPTION
**Pull request by marshallward**
The legacy `file_type` and `fieldtype` handles for field IO are replaced with the newer MOM IO types (`MOM_infra_file`, `MOM_field`), which provide new FMS-agnostic interfaces to the framework IO.

This also conforms to the new requirement of FMS IO requiring a domain. (Note that this may be relaxed in the future.)

Thanks to Kate Hedstrom (@kshedstrom) for identifying the issue and providing the first draft to this fix.

### CODE REVIEW

**Comment by marshallward** [comment]
@kshedstrom I seem unable to add you as a reviewer, but if you have a chance it would be good to get you feedback.

**Comment by marshallward** [comment]
There is still an error here: `ice_model.res.nc` is still not domain-decomposed even though `PARALLEL_RESTARTFILES` is True in `SIS_parameter_doc.all`.

This is the same error as in #195, and which I had thought this patch would address, but I suppose not.  I will continue to look into it.

**Comment by kshedstrom** [comment]
Yes, it's been working for me. Sorry, I thought I had posted, but I guess not.

**Comment by marshallward** [comment]
Sorry @kshedstrom, those comments weren't directed to you, I should have been more clear.  We are still seeing errors with FMS1, so we can't merge this yet.

**Comment by marshallward** [comment]
I think the associated issues on MOM6 have been fixed, and this is now ready for review.

**Comment by kshedstrom** [comment]
Yes, it's been working fine for me.

**Comment by marshallward** [comment]
@Hallberg-NOAA @adcroft This is ready for review

**Comment by adcroft** [comment]
This passed: https://gitlab.gfdl.noaa.gov/ogrp/SIS2/-/pipelines/19535 ✅

**Review by adcroft — APPROVED** [review]

**Pull request merged**
